apiVersion: skaffold/v4beta2
kind: Config
metadata:
  name: awa-bot
build:
  local:
    push: false
  artifacts:
  - image: ghcr.io/tashima42/awa-bot
    docker:
      dockerfile: Dockerfile.dev
      buildArgs:
        TELEGRAM_TOKEN: ${TELEGRAM_TOKEN}
        DB_USER: ${DB_USER}
        DB_HOST: ${DB_HOST}
        DB_PASSWORD: ${DB_PASSWORD}
        DB_PORT: ${DB_PORT}
        TZ: ${TZ}
    sync:
      auto: true
  - image: postgres
    context: bot
    buildpacks:
      builder: gcr.io/buildpacks/builder:v1
manifests:
  rawYaml:
  - k8s/bot-deployment.yaml
  - k8s/database-persistent-volume-claim.yaml
  - k8s/postgres-cluster-ip-service.yaml
  - k8s/postgres-deployment.yaml
