// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type MigrateInput struct {
	Version *string `json:"version"`
}

type MigrateOutput struct {
	Success *bool   `json:"success"`
	Version *string `json:"version"`
}

type RegisterWaterInput struct {
	Water *Water `json:"water"`
}

type RegisterWaterOutput struct {
	Success *bool `json:"success"`
}

type Water struct {
	ID        *string `json:"id"`
	UserID    *string `json:"userId"`
	Amount    *int    `json:"amount"`
	CreatedAt *string `json:"createdAt"`
	UpdatedAt *string `json:"updatedAt"`
}
