// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type MigrateInput struct {
	Version *string `json:"version"`
}

type MigrateOutput struct {
	Success *bool   `json:"success"`
	Version *string `json:"version"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
