apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: awa-api-certificate
  namespace: awa-bot
spec:
  dnsNames:
  - 'awa.tashima.space'
  issuerRef:
    kind: Issuer
    name: awa-bot-http
  secretName: awa-api-crt

