apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: awa-admin-certificate
  namespace: awa-bot
spec:
  dnsNames:
  - 'awa-admin.tashima.space'
  issuerRef:
    kind: Issuer
    name: awa-admin-http
  secretName: awa-admin-crt

