apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
 name: awa-bot-http
 namespace: awa-bot
spec:
 acme:
   email: cascade.trammel-0w@icloud.com
   server: https://acme-v02.api.letsencrypt.org/directory
   privateKeySecretRef:
     name: awa-bot-issuer-account-key
   solvers:
     - http01:
         ingress:
           class: traefik
